/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ch_epfl_scala_accessible_espeak_Espeak */

#ifndef _Included_ch_epfl_scala_accessible_espeak_Espeak
#define _Included_ch_epfl_scala_accessible_espeak_Espeak
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ch_epfl_scala_accessible_espeak_Espeak
 * Method:    nativeSynthesize
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ch_epfl_scala_accessible_espeak_Espeak_nativeSynthesize
  (JNIEnv *, jobject, jstring);

/*
 * Class:     ch_epfl_scala_accessible_espeak_Espeak
 * Method:    nativeStop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ch_epfl_scala_accessible_espeak_Espeak_nativeStop
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
